### ISSUE TITLE
Reduce number of tries if wayback machine is overloaded

### ISSUE THREAD

**Issue by barkoder** [overcast07/wayback-machine-spn-scripts#19]
The wayback machine is currently overloaded.

Getting a `The capture will start in ~3 hours, 40 minutes because our service is currently overloaded. You may close your browser window and the page will still be saved.` message.

So captures will not trigger until ~4 hours from time of capture.

Unfortunately `spn.sh` just keeps trying and pausing and trying and pausing for quite a long time(until `Job Failed`), just waiting for a captured URL(that won't come), without moving on to the next URLs on the list.
Could you add a way for the script to not wait if this particular message is generated upon save by the wayback machine?

So instead of saying a `Job Completed` it would say `Wayback Machine overloaded. Job Scheduled to be Completed in ~3 hours, 42 minutes` or something, while the script for that job sleeps in the background for aforementioned time and moves onto the next URL?

You probably know of a better way to resolve this error.

Thanks for the script @overcast07 . It's simply excellent!

**Comment by barkoder** [comment]
As an aside, they now seem to have reduced the number of parallel capture jobs from 8 to 6, so `429` errors galore.

curl -s -X GET -H 'Accept: application/json' -H 'Authorization: LOW S3accesskey:secret' https://web.archive.org/save/status/user

**Comment by overcast07** [comment]
I'm not sure if this is a normal situation that the script needs to handle. Jason Scott has [stated on Twitter](https://twitter.com/textfiles/status/1628576282983206914),
> Internet Archive is under attack. Someone is posting tens of thousands of posts, comments and other vectors and is crushing the system. We're working on it, sorry for the inconvenience.
While it would be possible to wait for 3 hours for all of the requests to be processed, I don't think the script would be particularly usable in this situation. anyway

Currently the script limits the number of child processes that can be spawned, both due to the number that you could realistically use under normal conditions, and inherent limits of how many processes your computer could run at the same time. To make the script make sense under these conditions, either you would be limited to about 60 captures every 4 hours or something ridiculous like that, or you would have to store job IDs and their corresponding wait times in text files, so that the API can be checked hours later when the job actually starts.

It would be theoretically possible to implement a solution where individual job IDs are stored in separate text files, but I would rather wait and see what happens, since I would really hope that this situation is temporary. If everyone's already waiting for 4 hours, making it easier to submit even more URLs to the backlog would just make the situation worse.

**Comment by overcast07** [comment]
I've checked just now and the situation appears to have gone back to normal for the time being, since it didn't tell me the service was overloaded and the captures went through immediately.

**Comment by AgostinoSturaro** [comment]
@overcast07 I still see similar message when I try to capture frequently-visited websites, like GitHub and the Microsoft doc pages.
Sometimes the capture gets delayed by just 10 minutes, sometimes more.
I'd say if you get a message that the capture is delayed, just don't retry, it will only make things worse.
Could you do that?

**Comment by overcast07** [comment]
One of the problems with SPN, especially when using it without authentication, is that the script has to get information by pattern matching the HTML source code of the response. Unfortunately, while there was previously support for handling delays, the format of the error message was changed without me realizing, and the matching doesn't work any more. So, before anything else gets fixed, I need to update that part of the script so that it correctly processes the amount of time to wait.

**Comment by overcast07** [comment]
Furthermore, because of the the capture rate now being limited server-side, the `-p` parameter no longer makes sense to set to a low value like 8, since if the website isn't extremely fragile then what the server does will be enough to avoid issues. That part of the script will also have to be changed.

**Comment by AgostinoSturaro** [comment]
It can be done, it's not the same as the overload issue.
There's actually [3 different issues](https://github.com/overcast07/wayback-machine-spn-scripts/issues/20#issuecomment-1445400101).

1. overloaded in general
2. too many requests about a website (by any number of users)
3. too many requests by the user

**Comment by overcast07** [comment]
I know it can be done, but I need to know if the format of the message is similar to the format of the other messages, which are

> The capture will start in ~[n] seconds because we are doing too many captures of [domain] right now. You may close your browser window and the page will still be saved.

> The capture will start in ~[m] hours, [n] minutes because our service is currently overloaded. You may close your browser window and the page will still be saved.

Matching for "capture will start in ..." works for both of these cases, but I haven't been able to get the other type of error message yet. I'm adding a `sleep` command so that the script actually waits for however long the delay is before starting the captures, which it previously didn't do.

**Comment by overcast07** [comment]
I've just managed to get this variant. I wonder how this happened lol
> The capture will start in ~ because our service is currently overloaded. You may close your browser window and the page will still be saved.

**Comment by AgostinoSturaro** [comment]
From the https://web.archive.org/save page, as an anonymous user, I got this one.

> Sorry
> 
> You have already reached the limit of active Save Page Now sessions. Please wait for a minute and then try again.

**Comment by overcast07** [comment]
That's perfectly normal and not a problem. The script will just retry the submitted URL until it works.

`lock.txt` exists specifically in order to handle this particular message: the file is created by one child process, other child processes don't attempt to retry URL submissions once the file is created (a file is necessary because otherwise the child processes can't pass data between each other), and then once the first child process submits its URL successfully, the file is removed, and only then are the remaining URLs retried.

**Comment by AgostinoSturaro** [comment]
Cool. Does it wait for the specified amount of time, or does it just retry in n seconds?

**Comment by overcast07** [comment]
It waits for 2 seconds between requests. The request itself takes several seconds, so the effect is that it's retried about every 5 seconds, but it depends on the latency of your internet connection.

> You have already reached the limit of active Save Page Now sessions. Please wait for a minute and then try again.

This doesn't literally mean that you have to wait for exactly one minute; if they meant that they would probably have written "wait for 1 minute". I think the intended meaning is "wait for a short time", since (I think) how it works is that once your number of concurrent active processes is below a certain number, it will let you start submitting more URLs.

**Comment by overcast07** [comment]
> I'm adding a `sleep` command so that the script actually waits for however long the delay is before starting the captures, which it previously didn't do.

This has been implemented now. I've been testing it myself and it appears to work correctly.

In the edge case that was originally reported, the new default behavior would be to submit 30 captures, spend 3 hours and 40 minutes waiting, and then check the SPN status API for the results. I don't think this would be ideal behavior in that situation, but at least it would (probably) work. Hopefully that sort of thing remains extremely rare.

**Comment by AgostinoSturaro** [comment]
If you can keep a list of:
- how many downloads have been completed in the last 60 seconds
- how many downloads are still being done

You could use it to avoid making the script hit the download limit.

**Comment by overcast07** [comment]
The script does not need to handle the limit of captures in the last 60 seconds by itself, as far as I can tell. SPN does not prevent you from submitting new URLs until there are multiple URLs actually being crawled by IA, so it kind of sorts itself out. I'm probably not going to adjust the script's behavior in this context.

The script already keeps track of how many capture jobs are active ("how many downloads are still being done"). However, this is not done in the same way that SPN keeps track of them, because the script also counts URLs that haven't been submitted yet; URLs that have been submitted but which are not being crawled yet; and URLs that have finished being crawled that the script doesn't know about yet. As such, there is no reason for the script's default number of maximum parallel capture jobs to correspond to the server-side limit.

We could use https://web.archive.org/save/status/user to get the number of active processes, but there is a limit to the overall rate of web requests that the script can send to web.archive.org. If you go over about 1 request per second, the site serves you a 429 error and you can't send any web requests for a minute. **The script can already tell if the limit has been reached by submitting new URLs**, which it already has to do anyway in order to work, so it would be counterproductive to also use a completely separate way of checking if the limit has been reached.

As far as I can tell, there is no time penalty associated with getting the "You have already reached the limit of active Save Page Now sessions" error message. It would not be meaningfully more efficient to switch to a different method, even if we didn't need to worry about getting 429 errors.

**Comment by overcast07** [comment]
I hope this explanation makes sense. I'm not trying to avoid working on it, but just trying to sort out the logic of whether or not it would actually be beneficial to make particular changes to the script.

**Comment by overcast07** [comment]
> how many downloads have been completed in the last 60 seconds

This isn't possible to calculate directly, because the script doesn't actually know when each capture job was completed. By default, if `-p` is set to 30, then the script also waits 30 seconds in between checking the status API for each URL, so if it gets the response that a capture was completed, then it could have been at any time in the past 30 seconds.

In the API response we do get the time it took to complete the job (e.g. `"duration_sec":12.8`) and the time that the main URL was captured (e.g. `"timestamp":"20230226190000"`), but I don't think this would take into account how long it took for the first URL to load, so it wouldn't be quite exact either.

**Comment by AgostinoSturaro** [comment]
The explanation makes sense overall. However, there's a couple of things I don't understand.

The API say when the capture was complete, so it would be possible to make a time difference and figure out how many downloads were completed within the last n seconds.
Add the number of downloads we are still waiting to complete, and you have the number to tell if we are within the limit.

However, I don't understand this part

> if -p is set to 30, then the script also waits 30 seconds in between checking the status API for each URL

If 30 downloads all start together, and they all complete within a minute, don't we hit the limit of 12 downloads per minute?
I'm surprised it works.

**Comment by overcast07** [comment]
> If 30 downloads all start together, and they all complete within a minute, don't we hit the limit of 12 downloads per minute?

The first ~4 are started together, but then after that the script waits 2.5 seconds between starting captures. It's specifically 2.5 seconds because of the need to avoid 429 errors. I haven't changed this behavior recently.

The limit of 12 captures per minute doesn't seem to be something that we need to be concerned about in the context of the script's code, because the server seems to take care of it. The delays that are introduced appear to effectively reduce the rate to 12 captures per minute even if you submit URLs more frequently than that.

**Comment by overcast07** [comment]
The messages are actually a little bit misleading. If it says

> The capture will start in ~1 minute because our service is currently overloaded.

this actually just means that you've hit the limit of 12 or 4 URLs per minute. In other words, it's saying _you're_ the one overloading the service. Of course, any individual user can't make much of a dent in their overall traffic, so it's not entirely true.

The difference in the length of the delays appears to be solely dependent on whether or not you're authenticated, and thereby whether your limit is 12 or 4.

**Comment by AgostinoSturaro** [comment]
Thanks for the explanation.

If needed, the field `status_ext ` does have a clearer error code, see page 5 and 6 of the [API doc](https://docs.google.com/document/d/1Nsv52MvSjbLb2PCpHlat0gkzw0EvtSgpKHu4mk0MnrA/edit)

> error:user-session-limit
> User has reached the limit of concurrent active capture sessions.

By the way, looking at the error code, some are not recoverable, for example:

> error:invalid-url-syntax
> Target URL syntax is not valid.
> 
> error:invalid-host-resolution
> Couldn’t resolve the target host.

You might want to treat them separately.

**Comment by overcast07** [comment]
These error codes could only be produced when initially submitting the URLs, but you can't get them if you aren't authenticated, because they aren't included in the HTML. But whether or not you're authenticated, it gives you the plain English error messages, so those strings can be checked for in both cases.

The script only checks error codes when dealing with the status API endpoint, which always returns JSON. You can't get these errors from that API, since if you're checking it in the first place then the relevant URL has already been submitted successfully.

The script only needs to check whether the error is one that is known to be recoverable. If the error isn't one of them then the capture job is immediately considered to be failed, so it doesn't need to have a list of all of the non-recoverable error strings.

> error:invalid-url-syntax
It's pretty much impossible to get this error from the API anyway. If you do try to archive invalid URLs for some reason, then it usually just gives you a `400 Bad Request` error instead of a normal JSON or HTML response.

**Comment by barkoder** [comment]
I have a text file containing 1000s of URLs.

I begin archiving them using `spn.sh -p 10 -nq -a 'S3KEY:S3PASS' -d 'skip_first_archive=1&capture_outlinks=1&capture_screenshot=1&if_not_archived_within=10000d&delay_wb_availability=1' list.txt`

For the first few URLs, I get

    The capture will start in ~4 seconds
	The capture will start in ~5 seconds
	The capture will start in ~6 seconds

And then out of nowhere,

	The capture will start in ~10 hours 40 minutes

This capture is now going to eat 1 `p` job for the next ~10 hours.
	
And then back again to

    The capture will start in ~5 seconds
	The capture will start in ~6 seconds

As spn.sh works its way down the list, more and more super long capture jobs slowly end up saturating all 10 available `p`s , eventually, completely stalling the archival process. All 10 parallel jobs are now sleeping.

Proposal - could you please add an additional flag, where the user may choose to have the job immediately fail(without any retries) if the "capture will start in time" message returned by the wayback machine, exceeds a certain time specified by the user in `Nh Nm Ns` ? 

I would rather spn.sh skip URLs on the list and move on to the rest of the list, than sleep for 10 hours. I could get back to the links I didn't capture later.

Thanks!

**Comment by overcast07** [comment]
Do you mean that the delayed captures should be treated as invalid or as failed?

If the capture is going to start in 10 hours then it will still start eventually, so to me it would make sense to mark them as failed, so that the script eventually ends up recording the capture without too much disruption to other captures.

I think it would make sense for the default maximum wait time to be an hour, under the assumption that if the amount of time is less than an hour then there would probably be a good reason for it. To be consistent with the other parts of the script the time would probably be stored in seconds.

**Comment by AgostinoSturaro** [comment]
I have faced this delay several times when manually requesting a capture from their UI. This often happens when snapshotting GitHub. It also seems like the pending capture still counts towards your max concurrent capture limit.
If you want to implement this, please do not make it a default.

**Comment by barkoder** [comment]
> Do you mean that the delayed captures should be treated as invalid or as failed?

Treat as invalid if time in the "capture will start in" message exceeds user specified time in a new flag.

*I don't know why I didn't use the word "invalid" in my previous comment. Even though you asked a very simple question. Sorry for the long-windedness of my previous comment @overcast07 .*
