### ISSUE TITLE
How to exclude multiple subdomains from being archived?

### ISSUE THREAD

**Issue by Fooftilly** [overcast07/wayback-machine-spn-scripts#31]
I am archiving a site that has many dead subdomains. Those subdomains used to be something like media.example.com, but many of them aren't really used anymore. My problem is that this script can easily exclude one subdomain (ex. api.example.com) but using regex to exclude them (ex. (media|api|arhive)\.example\.com) doesn't work. Is there any way to exclude multiple subdomains at once? If there isn't, could it be implemented?

**Comment by AlexanderRitter02** [comment]
Hi,
excluding several subdomains works fine on my side.
I've been using extensive subdomain filtering over the last year, for example:
```
'(id-neu|service|stellenmarkt|immobilien|produkte|zeitung|trauer|auto|flirt).schwarzwaelder-bote.de|(registrations|suche)\?'
```
As long as it is a valid regex it seems to work.

**Here are some things you could check and consider that may help you solve the issue:**
- If you entered the regex in the command line argument, maybe your shell swallowed special characters? You can check in the `exclude_pattern.txt` file if the regex is correct, and even modify it there on the fly.
- Verify the regex with the url it should filter on a site like https://regex101.com/
- Once a page has entered the `index.txt`, it is **not filtered** anymore, even if you adjust the regex. Filtering only happens when discovering outlinks.

Good luck.

**Comment by Fooftilly** [comment]
> * Once a page has entered the `index.txt`, it is **not filtered** anymore, even if you adjust the regex. Filtering only happens when discovering outlinks.

Thanks! This was the issue. I got flooded with thousand of links from certain subdomain, but I didn't know that the links from `index.txt` are not filtered again.
